### ISSUE TITLE
[Analysis Request]: Advanced SEM examples

### ISSUE THREAD

**Issue by andreifoldes** [OpenDevSci/LongDev-ABCD#9]
### Analysis Title

Advanced SEM examples

### Analysis Objective

Greetings,

Thanks for this resource. I wanted to ask when are the Advanced SEM examples planned to be released/uploaded?

### Dataset Details

-

### Statistical Methods

[Random-Intercept Crosslagged Panel Model](https://longitudinal.dev/examples/_15_Examples_RandomInterceptCrosslaggedPanelModels.qmd)
[Latent Curve Models with Structured Residuals](https://longitudinal.dev/examples/_16_Examples_LatentCurveModelsStructuredResiduals.qmd)

### Expected Outcomes

-

### Additional Notes

-

**Comment by swhawes** [comment]
Hi Andrei! Check back around the end of 2024/beginning of 2025. Currently, the plan is to revamp/update all code examples once the ABCD 6.0 public data release is available
